services:
  backend:
    build: .
    ports: ["3000:3001"]
  
  frontend:
    depends_on:
      - backend
    
    image: curlimages/curl:latest
    entrypoint: ["sh", "-c", "sleep 2 && curl http://backend:3001"]
