name: Test

on:
  push:
    branches:
      - main
      - new
    tags:
      - 1.2v
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-hadchi:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: nodejs setup
        uses: actions/setup-node@v3
        with: 
          node-version: 20
      - name: install npm
        run: npm ci

      - name: start
        run: npm start
